- name: Debug - Show ansible_limit
  debug:
    msg: "Ansible limit: {{ ansible_limit | default('Not Defined') }}"

# - name: Normalize ansible_limit and extract valid groups
#   set_fact:
#     limited_groups: "{{ ansible_limit.split(',') | map('trim') | select('in', groups.keys()) | list }}"




- name: Normalize ansible_limit and extract valid groups
  set_fact:
    limited_groups: "{{ ansible_limit.split(',') | map('trim') | list }}"
  when: ansible_limit is defined

- name: Fallback to all group prefixes if ansible_limit not defined
  set_fact:
    limited_groups: "{{ users | map(attribute='secret_name') | map('regex_replace', '^(.*?)_.*', '\\1') | unique | list }}"
  when: ansible_limit is not defined





- name: Debug - Show selected inventory groups
  debug:
    msg: "Processing inventory groups: {{ limited_groups }}"


- name: Filter users belonging to the selected groups
  set_fact:
    filtered_users: >-
      {{
        users |
        selectattr('secret_name', 'search', '(?i)^(' + (limited_groups | map('upper') | join('|')) + ')_') |
        list
      }}


- name: Debug - Filtered users
  debug:
    var: filtered_users



# - name: Generate passwords for filtered users
#   set_fact:
#     user_passwords: >-
#       {{
#         dict(
#           filtered_users | map(attribute='secret_name') |
#           zip(lookup('password', '/dev/null length=16', wantlist=True) | list)
#         )
#       }}
#   # no_log: true  # Hide passwords in logs

- name: Generate list of passwords for filtered users
  set_fact:
    temp_passwords: "{{ temp_passwords | default([]) + [lookup('password', '/dev/null length=16')] }}"
  loop: "{{ filtered_users }}"
  loop_control:
    label: "{{ item.secret_name }}"
  no_log: true

- name: Combine usernames and passwords into dictionary
  set_fact:
    user_passwords: >-
      {{
        dict(
          filtered_users | map(attribute='secret_name') |
          zip(temp_passwords)
        )
      }}
  no_log: true






- name: Debug - Show hosts in each selected group
  debug:
    msg: "Hosts in group {{ item }}: {{ groups[item] | default([]) }}"
  loop: "{{ limited_groups }}"


- name: Initialize group_passwords as an empty dictionary
  set_fact:
    group_passwords: {}

- name: Generate passwords for each group and store in a dictionary
  set_fact:
    group_passwords: "{{ group_passwords | combine({ item: lookup('password', '/dev/null length=16') }) }}"
  loop: "{{ limited_groups }}"
  # no_log: true


- name: Store group passwords globally
  add_host:
    name: "global_passwords"
    group_pwds: "{{ group_passwords }}"
  run_once: true
  # no_log: true  # Hide passwords in logs




