---
- name: Password rotation driver
  hosts: localhost
  gather_facts: no
  run_once: true

  tasks:
    - name: Build password rotation items
      include_role:
        name: fetch_generate_passwords

    - name: Execute password workflow
      include_role:
        name: rotate_credential
      vars:
        operation_type: "rotate"

    - name: Update Secret Server
      include_role:
        name: update_secret_server

    - name: Roll back password workflow
      include_role:
        name: rotate_passwords_ebs
      vars:
        operation_type: "rollback"

    - name: Send notification email
      include_role:
        name: send_email_notification