---
- name: Print OLAM Credentials
  hosts: localhost
  gather_facts: false

  vars:
    instance: "{{ instance }}"

  vars_files:
    - config/{{ instance }}.yaml

  tasks:
    - name: Print credential variables
      debug:
        msg:
          - "TGT_APPS_PASS={{ EBS_TGT_APPS_PASS | default('Not Set') }}"
          - "TGT_SYSTEM_PASS={{ EBS_TGT_SYSTEM_PASS | default('Not Set') }}"
          - "TGT_WEBLOGIC_PASS={{ EBS_TGT_WEBLOGIC_PASS | default('Not Set') }}"
          - "TGT_APPS_PASS_GEN={{ EBS_TGT_APPS_PASS_GEN | default('Not Set') }}"
          - "OLAM_PASS={{ OLAM_PASS | default('Not Set') }}"
