- name: Update Secret in Secret Server
  hosts: localhost
  gather_facts: no
  vars:
    final_password: "{{ lookup('password', '/dev/null', length=16, special_chars='@$#*') }}"
    # secret_id: 18830
    # token: "{ token }"
    # secret_name: "EXP"
    # site_id: 1               
    # field_id: 40                 
    # item_id: 253591                    
    # item_value: "{{ lookup('password', '/dev/null', length=16) }}"
    # comment: "made changes"
    # secret_server_username: "{ secret_server_username )"
    # secret_server_password: "{ secret_server_password }"
  vars_files:
    - vars/variables.yaml
  tasks:
    - name: update_password
      include_role:
        name: update_password
#     - name: Set variables for API call
#       set_fact:
#         api_url: "https://centroid.secretservercloud.com/api/v1/secrets/{{ secret_id }}"
#         #token: "AgIuMcA4xPOuA7BbM7PBBIHtpc6BczVo6TBXUqIJkAkmPn9UtNgJGmmdar7c2mmsgyUXBl9XQ3Jzav-fsG6xTHVG9uOL3sCijjDs6DcAY2COFBDRagKcA4aX89CB2dwwhJHLMSz1r9ZHdBuCnmMUadIjaVPi8QN6NTWzpaiPth7B0XdhZdiKgVgBatGQ1lZ3UYPtP42Hh3ruxvJvh4GNqQquEQ1ZQmMXQhexo_am0ROzHbZx2T2FOAOfs5evPbtijHuxEImog-7TBzFN5fmpkT1f_xk6FK5SpD2dLUQFm74Ebf9DN6KLaSjlcJdmWoVsuP7Fqfk-5E42N2TLt96aLK8dQzz8L5f6vp32CeoRUiCbloTZ7muBSMh0DoHDFo9p5zgenw4di0MDTQ1ro2wF1IZn3Plv2O2v3Xu21MQumR7j9tGJYhUC3XiPvgm1OOmos4ss9sipz-ZW3m9MtaDz50aqjRSXHBPO52jh4XX2n0QCe3Pz-Dqhm8w4YM8Dnx8IriGqUBDbTgT2xC_y0m4pw7C7bGeuzKBzpAgdZbUeYZZ2Qa01PiGk7GA35-2dCAf3Ix4TmX02D9tbTzgMGnl_0ugsoprwFwsfsqxgQZLSAEGEAOw50EHjIwV2XnA5tOP74ZXlz8gPyBcyoFAyKKQZ7NBSebwgrBJlyDSolEw9nFMFX4coSEx1oji2QoGNRG7AiC7gzstru0VC6xPVrNNCcnORndwRqiIEgDihjKcoLezPgw"
# #curl -v -H "Authorization: Bearer AgLbWy-NEvd3Xivp5EIuZZm2yovywO5zVPAdcpGErhiiD5qyByTOcM9J7R9ePTg5yp5_p-GqkWHhwL7S6rKrv-sYOw7ukRKH36y426_cv0UeAu5OpfQQ0mWWzrHTdZ0MPrpqThJhmAoZWEbOV_4E2O6lbGn9DzxigMYrSUrAgLw6x98Ekznh3LGnlOkjCVeWHOh9KJSKFPHsbz5Rb_a-MLOmUAfyTdt9j2-0DCrg_7SmA_43YDYjrn3myJeheQX4BJ5bV_JvhYRxkUpDtbwjc1Lr0AerZ0jW3MlOFuX0kNdyiqZ7x4KZRhErzYstSPkb2yuFxeB2BmzWZqdoJICM4X5UMDcEmRd0tc5Zou2pIswQLMR4fqb_iucHRycHJJSghxX0xHm2AcSlYFQOq5IOX3iyu-FHOizgxbipfpOkcCudmv2iSdnmlLbDUVmC4ufXjcKr6-smqpEaA7YtUATmVArhpTTTc2v4ngUJv09nLf9ionKwQ2QT_Yrah3O8G_jN-ZjsjC2KGkJMkEjw1prOC85iYiZjMRO-0PZDSKwVrddi67yxvzkqSu-lX__gawBlVFHqOCR4aRIjCy2Mdzbx1Ljeg229crSFKpHktmn7COYwI6rcSpGTRejDDdlABnv8ltEfwXLD8Ov9B0AZMACj2rV7-_EzMzek4SbNd8MFhCD4defEb-br_lKeA8oO1HMS50vGiaRu1CTNX1jYmRn_xpz9j7wJSsobBcNHApAY3vLhtg" https://centroid.secretservercloud.com/api/v1/secrets/18830

#     # - name: Retrieve existing secret
#     #   uri:
#     #     url: "{{ api_url }}"
#     #     method: GET
#     #     headers:
#     #       Authorization: "Bearer {{ token }}"
#     #     return_content: yes
#     #   register: existing_secret

#     - name: Retrieve the secret
#       uri:
#         url: "{{ api_url }}" #url: "{{ secret_server_url }}/secrets/{{ secret_id }}"
#         method: GET
#         headers:
#           Authorization: "Bearer {{ token }}"
#           Content-Type: "application/json"
#       register: get_secret_response
#       failed_when: get_secret_response.status != 200 

#     - name: Update password
#       uri:
#         url: "{{ api_url }}"
#         method: PUT
#         headers:
#           Authorization: "Bearer {{ token }}"
#           Content-Type: "application/json"
#         body_format: json
#         body:
#           id: 18830
#           name: "{{ secret_name }}"
#           siteId: "{{ site_id }}"
#           items:
#             - fieldId: "{{ field_id }}"
#               itemId: "{{ item_id }}"
#               itemValue: "{{ item_value }}"
#           active: true
#           comment: "{{ comment }}"
#         timeout: 30
#       register: update_response
#     - name: Set fact to filter password item
#       set_fact:
#         password_item: "{{ update_response.json['items'] | selectattr('slug', 'equalto', 'password') | list | first }}"

#     - name: Display the password item value
#       debug:
#         msg: "The password item value is {{ password_item.itemValue }}"
#       when: password_item is defined

    # - name:
    #   uri:
    #     url: "https://{{ api_host }}/api/v1/secrets/18830"
    #     method: PUT
    #     headers:
    #       Content-Type: "application/json"
    #       Authorization: "Bearer {{ api_token }}"
    #     body_format: json
    #     body:
    #       id: 18830
    #       name: "{{ secret_name }}"
    #       siteId: "{{ site_id }}"
    #       items:
    #         - fieldId: "{{ field_id }}"
    #           itemId: "{{ item_id }}"
    #           itemValue: "{{ item_value }}"
    #       active: true
    #       checkOutEnabled: true
    #       comment: "{{ comment }}"
    #       requiresComment: true
    #       sshKeyArgs:
    #         generatePassphrase: true
    #         generateSshKeys: true
    #     status_code: 200
    #   register: result

    # - name: Retrieve OAuth2 token from Secret Server
    #   uri:
    #     url: "https://centroid.secretservercloud.com/oauth2/token"
    #     method: POST
    #     headers:
    #       Content-Type: "application/x-www-form-urlencoded"
    #     body: 'username={{ secret_server_username }}&password={{ secret_server_password }}&grant_type=password'
    #     body_format: form-urlencoded
    #     return_content: yes
    #   register: token_response

