---
- name: Update datasource password
  hosts: all
  gather_facts: false
  run_once: true

  vars:
    instance: "{{ instance }}"

  vars_files:
    - config/{{ instance }}.yaml

  tasks:
    - name: Update datasource password
      include_role:
        name: update_datasource_password

    - name: Save datasource update results
      copy:
        dest: "/tmp/datasource_update_state.json"
        content: "{{ datasource_update_results | to_nice_json }}"
        mode: "0644"
      delegate_to: localhost
      run_once: true
