- name: Ensure secret name is set
  fail:
    msg: "secret_name is not defined!"
  when: secret_name is not defined

- name: Fetch secret from Secret Server for {{ secret_name }}
  uri:
    url: "{{ secret_server_base_url }}/api/v1/secrets/name/{{ secret_name | urlencode }}"
    method: GET
    headers:
      Authorization: "Bearer {{ secret_server_token }}"
      Content-Type: "application/json"
    return_content: yes
    status_code: 200
    validate_certs: yes
  delegate_to: localhost
  run_once: true
  register: fetched_secret

- name: Set current password from response
  set_fact:
    current_password: "{{ (fetched_secret.json.items[0].items | selectattr('fieldName', 'equalto', 'Password') | list)[0].itemValue }}"
  when: fetched_secret.json.items[0].items is defined

- name: Debug - Current password
  debug:
    msg: "Group {{ user_group }} has current password: {{ current_password }}"
