- name: "DEBUG: Inventory limit passed by OLAM"
  debug:
    msg: "Processing host: {{ inventory_hostname }} | Groups: {{ group_names }}"

- name: "Set primary group (assuming 1 group per host)"
  set_fact:
    user_group: "{{ group_names[0] }}"

- name: "DEBUG: User group determined"
  debug:
    msg: "Primary group selected: {{ user_group }}"

- name: Set a reference host for group {{ user_group }}
  set_fact:
    reference_host: "{{ groups[user_group] | first }}"

- name: Retrieve users from hostvars for group {{ user_group }}
  set_fact:
    group_users: "{{ hostvars[reference_host].users | selectattr('secret_name', 'defined') | list }}"

- name: Ensure group_users is not empty before proceeding
  fail:
    msg: "No valid users found for group {{ user_group }}. Check inventory configuration."
  when: group_users | length == 0

- name: Extract user details for group {{ user_group }}
  set_fact:
    user_details:
      username: "{{ group_users[0].secret_name.split('_')[-1] | lower }}"
      email_recipients: "{{ group_users[0].email_recipients | default([]) }}"
      secret_name: "{{ group_users[0].secret_name }}"

- name: Debug - Show extracted user details
  debug:
    msg: "Group: {{ user_group }}, Username: {{ user_details.username }}, Secret Name: {{ user_details.secret_name }}, Email Recipients: {{ user_details.email_recipients }}"


- name: Fetch secret from Secret Server for {{ user_details.secret_name }}
  uri:
    url: "{{ secret_server_base_url }}/api/v1/secrets/name/{{ user_details.secret_name | urlencode }}"
    method: GET
    headers:
      Authorization: "Bearer {{ tkn }}"
      Content-Type: "application/json"
    return_content: yes
    status_code: 200
    validate_certs: yes
  delegate_to: localhost
  run_once: true
  register: fetched_secret

- name: Set current password from response
  set_fact:
    current_password: "{{ (fetched_secret.json.items[0].items | selectattr('fieldName', 'equalto', 'Password') | list)[0].itemValue }}"
  when: fetched_secret.json.items[0].items is defined

- name: Debug - Current password
  debug:
    msg: "Group {{ user_group }} current password fetched: {{ current_password }}"
