# all:
#   children:
#     CENTROID_Prod:
#       # children:
#       #   Cen_Prod_APP:
#       #     hosts:
#       #       app_server01:
#       #         ansible_host: 10.10.10.1
#       #       app_server02:
#       #         ansible_host: 10.10.10.2
#       #   Cen_Prod_DB:
#       #     hosts:
#       #       db_server01:
#       #         ansible_host: 10.10.10.3
#     CENTROID_NonProd:
#       children:
#         Cen_NonProd_APP:
#           hosts:
#             app_server03:
#               ansible_host: 10.10.20.1
#             app_server04:
#               ansible_host: 10.10.20.2
#         Cen_NonProd_DB:
#           hosts:
#             db_server02:
#               ansible_host: 10.10.20.3