- name: Generate a random password
  set_fact:
    final_password: "{{ lookup('password', '/dev/null', length=16, special_chars='@$#*') }}"
    cacheable: true
  delegate_to: localhost
  no_log: true


- name: Reset password for user
  shell: echo "{{ final_password }}" | passwd --stdin {{ user_details.username }}
  become: yes
  no_log: false

- name: Register host and user
  set_fact:
    host_result:
      host: "{{ inventory_hostname }}"
      user: "{{ user_details.username }}"

- name: Share final_password with localhost
  set_fact:
    final_pass: "{{ final_password }}"
  delegate_to: localhost
  run_once: true
  no_log: true


- name: Update password in Secret Server
  include_role:
    name: update_password
  vars:
    final_password: "{{ final_pass }}"
    secret_name: "{{ user_details.secret_name }}"
  run_once: true


- name: Aggregate results
  set_fact:
    password_reset_results: "{{ ansible_play_hosts | map('extract', hostvars, ['host_result']) | list }}"
  run_once: true
  delegate_to: localhost



- name: Send an email to the user
  community.general.mail:
    host: "{{ smtp_server }}"
    port: "{{ smtp_port }}"
    from: "{{ email_sender }}"
    to: "{{ user_details.email_recipients | join(', ') }}"
    subject: "Password Rotation - {{ user_details.username }}"
    body: |
      Hi, 

      The password for the following user has been successfully rotated:
      
      {% for result in password_reset_results %}
      Host: {{ result.host }} | User: {{ result.user }}
      {% endfor %}


      You can retrieve updated password from the Secret Server using the following details:
      Secret Name: {{ user_details.secret_name }}
      Secret ID: {{ secret_id }}

      URL: https://centroid.secretservercloud.com/app/#/secrets/{{ secret_id }}/general


      Thanks & Regards,
      Automation Team


