- name: Generate a random password
  set_fact:
    final_password: "{{ lookup('password', '/dev/null', length=16, special_chars='@$#*') }}"

- name: Reset password for user
  shell: echo "{{ final_password }}" | passwd --stdin {{ user_details.username }}
  become: yes

- name: Update password in Secret Server
  include_role:
    name: update_password
  vars:
    final_password: "{{ final_password }}"
    secret_id: "{{ user_details.secret_id }}"
    secret_name: "{{ user_details.secret_name }}"

- name: Send an email to the user
  community.general.mail:
    host: "{{ smtp_server }}"
    port: "{{ smtp_port }}"
    from: "{{ email_sender }}"
    to: "{{ user_details.email_recipient }}"
    subject: "Password Rotation - {{ user_details.username }}"
    body: |
      Hi {{ user_details.username }},

      Your password has been successfully rotated.

      You can retrieve your updated password from the Secret Server using the following details:
      Secret Name: {{ user_details.secret_name }}
      Secret ID: {{ user_details.secret_id }}

      URL: https://centroid.secretservercloud.com/app/#/secrets/{{ user_details.secret_id }}/general

      Thanks & Regards,
      Automation Team