---
# -------------------------------------------------------------------
# Secret Server: Retrieve and capture current secret details
# -------------------------------------------------------------------
- name: Debug - Verify received secret_name and group_name
  debug:
    msg: "Secret Name: {{ secret_name }}"

- name: Set API URL for secret retrieval
  set_fact:
    api_url: "{{ secret_server_base_url }}/api/v1/secrets?filter.searchField=name&filter.searchText={{ secret_name }}"

- name: Retrieve matching secrets from Secret Server
  uri:
    url: "{{ api_url }}"
    method: GET
    headers:
      Authorization: "Bearer {{ tkn }}"
    return_content: yes
  register: secrets_found
  delegate_to: localhost

- name: Debug API response from Secret Server
  debug:
    var: secrets_found.json

- name: Find the ID for the specified secret_name
  set_fact:
    found_secret_id: "{{ secrets_found.json.records | selectattr('name', 'equalto', secret_name) | map(attribute='id') | list | first }}"

- name: Debug found_secret_id
  debug:
    msg: "Secret ID found: {{ found_secret_id }} for secret_name: {{ secret_name }}"

- name: Set API URL to get the secret details from the secret ID
  set_fact:
    api_url2: "{{ secret_server_base_url }}/api/v1/secrets/{{ found_secret_id }}"

- name: Retrieve existing secret details
  uri:
    url: "{{ api_url2 }}"
    method: GET
    headers:
      Authorization: "Bearer {{ tkn }}"
    return_content: yes
  register: existing_secret
  delegate_to: localhost
  #no_log: true

- name: Set secret details facts and capture old password
  set_fact:
    site_id: "{{ existing_secret.json['siteId'] }}"
    folder_id: "{{ existing_secret.json['folderId'] }}"
    field_id: "{{ (existing_secret.json['items'] | selectattr('slug', 'equalto', 'password') | first).fieldId }}"
    item_id: "{{ (existing_secret.json['items'] | selectattr('slug', 'equalto', 'password') | first).itemId }}"
    secret_name: "{{ existing_secret.json['name'] }}"
    secret_id: "{{ existing_secret.json.id }}"
    comment: "Updating password for secret: {{ secret_name }}"
    old_password: "{{ (existing_secret.json['items'] | selectattr('slug', 'equalto', 'password') | first).itemValue }}"
  #no_log: true

# -------------------------------------------------------------------
# Generate a new password for rotation
# -------------------------------------------------------------------
- name: Generate new password
  set_fact:
    final_password: "{{ lookup('password', '/dev/null', length=16) }}"

  #no_log: true

# -------------------------------------------------------------------
# Oracle DB: Update password and then update Secret Server (with rollback)
# -------------------------------------------------------------------
- block:
    - name: Update password for target Oracle user on CDB
      shell: |
        source {{ ORACLE_HOME }}/{{ CDB_ENV }}
        sqlplus / as sysdba <<EOF
        ALTER USER {{ target_user | upper }} IDENTIFIED BY "{{ final_password }}";
        EXIT;
        EOF
      when: dbtype == "CDB"
      register: password_change_cdb

    - name: Update password for target Oracle user on PDB
      shell: |
        source {{ ORACLE_HOME }}/{{ PDB_ENV }}
        sqlplus / as sysdba <<EOF
        ALTER SESSION SET CONTAINER=EBS_PDB;
        ALTER USER {{ target_user | upper }} IDENTIFIED BY "{{ final_password }}";
        EXIT;
        EOF
      when: dbtype == "PDB"
      register: password_change_pdb

    - name: Validate new Oracle password when CDB
      shell: |
        source {{ ORACLE_HOME }}/{{ CDB_ENV }}
        sqlplus "{{ target_user | upper }}"/"{{ final_password }}"@EBSTRGT as sysdba <<EOF
        EXIT;
        EOF
      args:
        executable: /bin/bash
      when: dbtype == "CDB"
      register: validation
      changed_when: false
    
    - name: Validate new Oracle password when PDB
      shell: |
        source {{ ORACLE_HOME }}/{{ PDB_ENV }}
        sqlplus "{{ target_user | upper }}"/"{{ final_password }}"@EBSTRGT as sysdba <<EOF
        EXIT;
        EOF
      args:
        executable: /bin/bash
      when: dbtype == "PDB"
      register: validation
      changed_when: false

    - name: Update Secret Server with the new password
      uri:
        url: "{{ api_url2 }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ tkn }}"
          Content-Type: "application/json"
        body_format: json
        body:
          id: "{{ secret_id }}"
          name: "{{ secret_name }}"
          siteId: "{{ site_id }}"
          folderId: "{{ folder_id }}"
          items:
            - fieldId: "{{ field_id }}"
              itemId: "{{ item_id }}"
              itemValue: "{{ final_password }}"
          active: true
          comment: "{{ comment }}"
      register: update_response
      delegate_to: localhost
      #no_log: true
      failed_when: update_response.status not in [200, 201, 204]

    - name: Send success email notification
      mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        from: "{{ email_sender }}"
        subject: "Password Rotation Succeeded for {{ target_user }}"
        #to: "{{ user_details.email_recipients | join(', ') }}"
        to: "sampat.andavarapu@centroid.com"
        body: >
          Password rotation succeeded for {{ target_user }}.
          The Oracle DB password and Secret Server have been updated successfully.
  rescue:
    - name: Rollback Oracle DB password update on CDB
      shell: |
        source {{ ORACLE_HOME }}/{{ CDB_ENV }}
        sqlplus / as sysdba <<EOF
        ALTER USER {{ target_user | upper }} IDENTIFIED BY "{{ old_password }}";
        EXIT;
        EOF
      when: dbtype == "CDB"
      register: rollback_cdb

    - name: Rollback Oracle DB password update on PDB
      shell: |
        source {{ ORACLE_HOME }}/{{ CDB_ENV }}
        sqlplus / as sysdba <<EOF
        ALTER SESSION SET CONTAINER=EBS_PDB;
        ALTER USER {{ target_user | upper }} IDENTIFIED BY "{{ old_password }}";
        EXIT;
        EOF
      when: dbtype == "PDB"
      register: rollback_pdb
    
    - name: Validate old Oracle password when CDB
      shell: |
        source {{ ORACLE_HOME }}/{{ CDB_ENV }}
        sqlplus "{{ target_user | upper }}"/"{{ old_password }}"@EBSTRGT as sysdba <<EOF
        EXIT;
        EOF
      args:
        executable: /bin/bash
      when: dbtype == "CDB"
      register: validation
      changed_when: false
    
    - name: Validate old Oracle password when PDB
      shell: |
        source {{ ORACLE_HOME }}/{{ PDB_ENV }}
        sqlplus "{{ target_user | upper }}"/"{{ old_password }}"@EBSTRGT as sysdba <<EOF
        EXIT;
        EOF
      args:
        executable: /bin/bash
      when: dbtype == "PDB"
      register: validation
      changed_when: false
    
    - name: Send failure email notification
      mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        from: "{{ email_sender }}"
        subject: "Password Rotation Failed for {{ target_user }}"
        to: sampat.andavarapu@centroid.com
        body: >
          Password rotation failed for {{ target_user }}.
          The Secret Server update did not succeed. The Oracle DB password has been rolled back to its previous value.
      delegate_to: localhost