# ---
# - name: Check account status of the target Oracle user
#   shell: |
#     source {{ ORACLE_HOME }}/{{ CDB_ENV }}
#     sqlplus / as sysdba <<EOF | grep -o 'OPEN'
#     SET PAGES 0 FEEDBACK OFF VERIFY OFF HEADING OFF;
#     SELECT account_status FROM dba_users WHERE username = '{{ target_user | upper} }}';
#     EXIT;
#     EOF
#   args:
#     executable: /bin/bash
#   register: account_status
#   changed_when: false

# - name: Debug Show account status output
#   debug:
#     msg: "Account status: {{ account_status.stdout | trim }}"

# - name: Change password for user if account is OPEN
#   shell: |
#     source {{ ORACLE_HOME }}/{{ CDB_ENV }}
#     sqlplus / as sysdba <<EOF
#     ALTER USER {{ target_user | upper}} IDENTIFIED BY "{{ new_password }}";
#     EXIT;
#     EOF
#   args:
#     executable: /bin/bash
#   when: account_status.stdout | trim == "OPEN"
#   register: password_change

# - name: Debug Show password change result
#   debug:
#     var: password_change.stdout
#   when: password_change is defined

