- name: Initialize results list
  set_fact:
    processed_items: []

- name: Process each rotation item
  include_tasks: rotate_on_host.yml
  loop: "{{ password_rotation_items }}"
  loop_control:
    loop_var: rotation_item
  when: >
    (operation_type == 'rotate') or
    (
      operation_type == 'rollback' and
      (
        rotation_item.apply_success == true and
        (
          rotation_item.secretserver_success == false
        )
      )
    )
  # when: >
  #   (operation_type == 'rotate') or
  #   (
  #     operation_type == 'rollback' and
  #     (
  #       rotation_item.apply_success == true and
  #       (
  #         rotation_item.post_success == false or
  #         rotation_item.secretserver_success == false
  #       )
  #     )
  #   )

# - name: Add back items that were not processed
#   set_fact:
#     processed_items: "{{ processed_items + [item] }}"
#   loop: "{{ password_rotation_items }}"
#   loop_control:
#     loop_var: item
#   when: item not in processed_items

- name: Update global list
  set_fact:
    password_rotation_items: "{{ processed_items }}"