- name: Update password in Secret Server for each group
  include_role:
    name: update_password
  vars:
    secret_name: "{{ user_details.secret_name }}"
    final_password: "{{ final_pwd }}"
    secret_id: "{{ found_secret_id }}"
    group_name: "{{ group_names[0] }}"

