- name: Loop through users defined in inventory group
  set_fact:
    user_item: "{{ item }}"
  with_items: "{{ users }}"

- name: Debug - Verify received secret_name
  debug:
    msg: "Fetching password for Secret: {{ user_item.secret_name }}"

- name: Set API URL to search for secret
  set_fact:
    api_url: "{{ secret_server_base_url }}/api/v1/secrets?filter.searchField=name&filter.searchText={{ user_item.secret_name }}"
    tkn: "{{ tkn }}"

- name: Retrieve matching secret
  uri:
    url: "{{ api_url }}"
    method: GET
    headers:
      Authorization: "Bearer {{ tkn }}"
    return_content: yes
  register: secrets_found
  delegate_to: localhost

- name: Find the secret ID
  set_fact:
    found_secret_id: "{{ secrets_found.json.records | selectattr('name', 'equalto', user_item.secret_name) | map(attribute='id') | list | first }}"

- name: Retrieve full secret details using secret ID
  uri:
    url: "{{ secret_server_base_url }}/api/v1/secrets/{{ found_secret_id }}"
    method: GET
    headers:
      Authorization: "Bearer {{ tkn }}"
    return_content: yes
  register: existing_secret
  delegate_to: localhost

- name: Extract existing password and related info
  set_fact:
    existing_pwd: "{{ (existing_secret.json['items'] | selectattr('slug', 'equalto', 'password') | first).itemValue }}"
    secret_user: "{{ user_item.secret_name.split('_')[-1] }}"
    secret_group: "{{ user_item.secret_name.split('_')[:-1] | join('_') }}"
    fetched_secret_name: "{{ existing_secret.json['name'] }}"
