---
- name: Debug – verifying secret_name & group_name
  debug:
    msg: "Secret: {{ secret_name }} in group {{ group_name }}"

- name: Set API URL for secret search
  set_fact:
    api_url: "{{ secret_server_base_url }}/api/v1/secrets?filter.searchField=name&filter.searchText={{ secret_name }}"

- name: Search secrets on Secret Server
  uri:
    url: "{{ api_url }}"
    method: GET
    headers:
      Authorization: "Bearer {{ tkn }}"
    return_content: yes
  register: secrets_found
  delegate_to: localhost

- name: Extract secret ID for {{ secret_name }}
  set_fact:
    found_secret_id: >-
      {{ (secrets_found.json.records
           | selectattr('name','equalto', secret_name)
           | map(attribute='id')
           | list
         )[0] }}

- name: Fetch full secret details
  uri:
    url: "{{ secret_server_base_url }}/api/v1/secrets/{{ found_secret_id }}"
    method: GET
    headers:
      Authorization: "Bearer {{ tkn }}"
    return_content: yes
  register: existing_secret
  delegate_to: localhost

- name: Set secret details facts and capture old password
  set_fact:
    secret_details_dict:
      site_id: "{{ existing_secret.json['siteId'] }}"
      folder_id: "{{ existing_secret.json['folderId'] }}"
      field_id: "{{ (existing_secret.json['items'] | selectattr('slug', 'equalto', 'password') | first).fieldId }}"
      item_id: "{{ (existing_secret.json['items'] | selectattr('slug', 'equalto', 'password') | first).itemId }}"
      secret_name: "{{ existing_secret.json['name'] }}"
      secret_id: "{{ existing_secret.json.id }}"
      comment: "Updating password for secret: {{ secret_name }}"

- name: Capture old_password
  set_fact:
    old_password: >-
      {{ (existing_secret.json['items']
           | selectattr('slug','equalto','password')
           | first
         ).itemValue }}

- name: Generate a new random password
  set_fact:
    new_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters+digits') }}"

- name: Append record for {{ secret_name }} in {{ group_name }}
  set_fact:
    password_rotation_items: >-
      {{ password_rotation_items + [ {
          'group':               group_name,
          'retrieved_password':  old_password,
          'generated_password':  new_password,
          'password_success':    false,
          'secretserver_success':false,
          'user_details': user_entry,
          'secret_details': secret_details_dict
        } ] }}

