- name: Initialize flags for {{ rotation_item.secret_name }} in {{ rotation_item.group }}
  set_fact:
    failed_rollbacks: []
    rollback_db_success: true

- name: Rotate password on each host of {{ rotation_item.group }}
  loop: "{{ groups[rotation_item.group] }}"
  loop_control:
    loop_var: target_host
  include_tasks: process_item.yml

- name: Append rollback results for {{ rotation_item.user_details.user }}
  set_fact:
    updated_items: >-
      {{ updated_items + [ rotation_item
          | combine({
              'rollback_db_success': rollback_db_success,
              'failed_rollbacks': failed_rollbacks
            }) ] }}
