---
- block:

    - name: Derive target password
      set_fact:
        target_password: >-
          {{
            rotation_item.generated_password
            if operation_type == 'rotate'
            else rotation_item.retrieved_password
          }}

        previous_password: >-
          {{
            rotation_item.retrieved_password
            if operation_type == 'rotate'
            else rotation_item.generated_password
          }}
      
    - name: Determine app tier hosts (list, group, multi‑node or single‑node)
      set_fact:
        app_tier_hosts: >-
          {{
            (hostvars[target_host].app_tier_group | type_debug == 'list')
            | ternary(
                hostvars[target_host].app_tier_group,
                groups[hostvars[target_host].app_tier_group]
                if hostvars[target_host].app_tier_group is string
                and hostvars[target_host].app_tier_group in groups
                else [target_host]
            )
          }}
  
    - name: Stop all EBS services
      shell: |
        cd /tmp
        source {{ hostvars[target_host].EBS_ENV_FILE }} run
        { echo "apps"; echo "{{ rotation_item.dependent_passwords.apps_password  }}"; echo "{{ system_password }}"; } | adstpall.sh apps@{{ hostvars[target_host].DB_SID }}
      args:
        executable: /bin/bash
      delegate_to: "{{ item }}"
      loop: "{{ app_tier_hosts }}"
      when: restart_services | default(false)
      become: yes
      become_user: "{{ hostvars[target_host].ebs_owner }}"
      register: stop_services_result
      failed_when: stop_services_result.rc != 0

    - name: Start Admin Server
      shell: |
        . {{ hostvars[target_host].EBS_ENV_FILE }}

        $ADMIN_SCRIPTS_HOME/adadminsrvctl.sh start
      args:
        executable: /bin/bash
      delegate_to: "{{ target_host }}"
      register: admin_server_start_result
      failed_when: admin_server_start_result.rc != 0

    - name: Change WebLogic admin password
      expect:
        command: >
          perl $FND_TOP/patch/115/bin/txkUpdateEBSDomain.pl
          -action=updateAdminPassword
        responses:
          '.*Enter.*APPS password.*':
            "{{ rotation_item.dependent_passwords.apps_password }}"

          '.*Enter.*WebLogic password.*':
            "{{ previous_password }}"

          '.*Enter.*new.*WebLogic password.*':
            "{{ target_password }}"

          '.*Do you want to continue.*':
            "Y"

        timeout: 1800
      args:
        chdir: "$FND_TOP/patch/115/bin"
      environment:
        CONTEXT_FILE: "{{ hostvars[target_host].CONTEXT_FILE }}"
      delegate_to: "{{ target_host }}"
      register: weblogic_password_change_result
      failed_when: weblogic_password_change_result.rc != 0
    
    
    - name: Mark apply success
      set_fact:
        apply_success: true

  rescue:

    - name: Mark apply failure
      set_fact:
        apply_success: false

        apply_errors: >-
          {{
            apply_errors + [{
              'msg': ansible_failed_result.msg | default('WebLogic apply failed')
            }]
          }}

    - fail:
        msg: "WebLogic apply phase failed"