---
- name: Reset the user password on target hosts
  shell: echo "{{ final_password }}" | passwd --stdin {{ username }}
  become: yes

- name: Register host and user
  set_fact:
    host_result:
      host: "{{ inventory_hostname }}"
      user: "{{ username }}"
      
- name: Collect host password reset results
#  local_action: set_fact
  set_fact:
    password_reset_results: "{{ password_reset_results | default([]) + [ {'host': inventory_hostname, 'user': username} ] }}"
  delegate_to: localhost
  #run_once: false
